export const ATUALIZA_PROJETO = 'ATUALIZA_PROJETO';
export const ADICIONA_PROJETO = 'ADICIONA_PROJETO';
export const REMOVE_PROJETO = 'REMOVE_PROJETO';

export const NOTIFICAR = 'NOTIFICAR';
export const REMOVER_NOTIFICACAO = 'REMOVER_NOTIFICACAO';